- id: '1740089652319'
  alias: Wake Up!
  description: ''
  triggers: []
  conditions: []
  actions:
  - data: {}
    target:
      entity_id:
      - automation.turn_on_tv_bufo
    action: automation.trigger
  - type: turn_on
    device_id: 09564afa5f5036ac8434885497f9ad56
    entity_id: c1f7d6f098ce6281b32b8f7e8db72789
    domain: light
  - type: turn_on
    device_id: d32241669db03c603baa5a527aac6c23
    entity_id: light.reading_light
    domain: light
  - type: turn_on
    device_id: 0cd71aab4097cbba429d8e6ce3669c05
    entity_id: switch.mood_wire_light
    domain: switch
  mode: single
- id: '1740090856944'
  alias: Turn on TV
  description: ''
  triggers: []
  conditions: []
  actions:
  - data: {}
    action: media_player.turn_on
    target:
      device_id: e0f4382e296225f9b3f3f1724fe964d8
  - data: {}
    action: media_player.turn_off
    target:
      device_id: e0f4382e296225f9b3f3f1724fe964d8
  mode: single
- id: '1740091188870'
  alias: Sleepy Time...
  description: ''
  triggers: []
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      device_id:
      - f452c94d32c0e74ff9cf45a8fbd96e77
      - aab3d01b268851dc34c32c8a615d4960
      - 0cd71aab4097cbba429d8e6ce3669c05
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.desk_light
      - light.reading_light
  - action: media_player.turn_off
    metadata: {}
    data: {}
    target:
      device_id:
      - e0f4382e296225f9b3f3f1724fe964d8
      - 3718ded81c31df2e8aeb964cbd7203df
  mode: single
- id: '1740091718203'
  alias: Arriving Home at Night
  description: ''
  triggers:
  - trigger: zone
    entity_id: person.roos
    zone: zone.home
    event: enter
  conditions:
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.seppe
      zone: zone.home
  - condition: sun
    after: sunset
  actions:
  - action: automation.trigger
    metadata: {}
    data:
      skip_condition: true
    target:
      entity_id: automation.wake_up
  mode: single
