# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include includes/customize.yaml

# ---
# Entities
# ---
sensor: !include_dir_merge_list includes/entities/sensor
zone: !include includes/entities/zone.yaml

# ---
# Services
# ---
rest_command: !include_dir_merge_named includes/services/rest_command
notify: !include_dir_merge_list includes/services/notify

# ---
# Automations
# ---
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
automation manual: !include includes/automations.yaml
automation ui: !include automations.yaml

# ---
# Interfaces
# ---
frontend:
  themes: !include_dir_merge_named themes/

google_assistant:
  project_id: home-assistant-140f3
  service_account: !include SERVICE-ACCOUNT.json
  report_state: true
  exposed_domains:
    - switch
    - light
  secure_devices_pin: !secret google_secure_devices_pin

# ---
# Other
# ---
group: !include includes/groups.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

tts:
  - platform: google_translate

