- id: '1659384053123'
  alias: Laundromat still on
  description: ''
  triggers:
  - at: 06:00:00
    trigger: time
  conditions:
  - condition: device
    type: is_on
    device_id: 779e72f28ce08228de351b98df2535f5
    entity_id: switch.laundromat
    domain: switch
  actions:
  - action: notify.mobile_app_fratercula
    metadata: {}
    data:
      title: Laundry machine still online!
      message: Heya dummy -- you forgot the laundry!
  mode: single
